"""Security category normalization shared by reviewers, calibration, and cross-PR analysis."""

import re

SECURITY_CATEGORIES = {
    "authentication",
    "authorization",
    "ci-security",
    "code-injection",
    "command-injection",
    "config-injection",
    "crypto",
    "csrf",
    "data-leak",
    "dependency-deprecated",
    "dependency-version-range",
    "dependency-vulnerability",
    "hardcoded-secrets",
    "insecure-download",
    "insecure-deserialization",
    "open-redirect",
    "path-traversal",
    "prototype-pollution",
    "rce",
    "sandbox-escape",
    "security",
    "sql-injection",
    "ssrf",
    "supply-chain-risk",
    "unsafe-block",
    "unsafe-deserialization",
    "unsafe-transmute",
    "unsafe-usage",
    "vulnerable-dependency",
    "xss",
    "xss-bypass",
    "xxe",
}

_ALIASES = {
    "arbitrary-code-execution": "rce",
    "client-secrets": "hardcoded-secrets",
    "client-side-code-execution": "code-injection",
    "code-execution": "code-injection",
    "critical-security-vulnerability": "rce",
    "deserialization": "insecure-deserialization",
    "directory-traversal": "path-traversal",
    "empty-catch": "exception-handling",
    "eval": "code-injection",
    "eval-injection": "code-injection",
    "file-disclosure": "path-traversal",
    "file-path-traversal": "path-traversal",
    "hardcoded-secret": "hardcoded-secrets",
    "hardcoded-token": "hardcoded-secrets",
    "insecure-crypto": "crypto",
    "insecure-hash": "crypto",
    "insecure-randomness": "crypto",
    "insecure-yaml-load": "insecure-deserialization",
    "known-vulnerability": "dependency-vulnerability",
    "malicious-dependency": "supply-chain-risk",
    "alt-text": "missing-alt",
    "image-alt": "missing-alt",
    "missing-image-alt": "missing-alt",
    "missing-alt-text": "missing-alt",
    "missing-accessible-label": "missing-label",
    "missing-accessible-name": "missing-label",
    "missing-form-label": "missing-label",
    "unlabeled-form-control": "missing-label",
    "open-redirection": "open-redirect",
    "os-command-injection": "command-injection",
    "optional-unsafe-get": "null-safety",
    "remote-code-execution": "rce",
    "rce-via-deserialization": "insecure-deserialization",
    "react-side-effects": "side-effect-in-render",
    "secret-exposure": "hardcoded-secrets",
    "secret-leak": "hardcoded-secrets",
    "secret-leakage": "data-leak",
    "security-xss": "xss",
    "sensitive-data-exposure": "data-leak",
    "shell-injection": "command-injection",
    "supply-chain": "supply-chain-risk",
    "supply-chain-attack": "supply-chain-risk",
    "supply-chain-attack-history": "supply-chain-risk",
    "supply-chain-attack-risk": "supply-chain-risk",
    "token-leak": "data-leak",
    "token-storage": "data-leak",
    "unsafe-code": "unsafe-block",
    "unsafe-code-execution": "code-injection",
    "unsafe-yaml": "insecure-deserialization",
    "unsafe-trigger": "ci-security",
    "malicious-script": "supply-chain-risk",
    "dangerously-set-innerhtml": "xss",
    "dangerous-html": "xss",
    "known-vulnerable-dependency": "dependency-vulnerability",
    "outdated-dependency": "dependency-deprecated",
    "deprecated-dependency": "dependency-deprecated",
    "unbounded-dependency-version": "dependency-version-range",
    "unlocked-dependency": "dependency-version-range",
    "unpinned-dependency": "dependency-version-range",
    "unsafe-html": "xss",
    "version-unpinned": "dependency-version-range",
    "version-not-pinned": "dependency-version-range",
    "version-range": "dependency-version-range",
    "vulnerable-dependency": "dependency-vulnerability",
    "weak-crypto": "crypto",
    "weak-cryptography": "crypto",
    "weak-hash": "crypto",
    "side-effect-in-computed": "computed-side-effect",
    "panic": "panic-risk",
    "严重安全漏洞": "rce",
    "严重过时依赖": "dependency-deprecated",
    "供应链攻击历史": "supply-chain-risk",
    "供应链攻击风险": "supply-chain-risk",
    "已知漏洞依赖": "dependency-vulnerability",
    "版本范围不安全": "dependency-version-range",
    "过时依赖": "dependency-deprecated",
}


def normalize_category(category: str) -> str:
    """Return a stable finding category while preserving non-security labels."""
    raw = str(category or "").strip().lower().replace("_", "-").replace(" ", "-")
    normalized = re.sub(r"-+", "-", raw).strip("-")
    return _ALIASES.get(normalized, normalized)


def is_security_category(category: str) -> bool:
    """Whether a finding category should be treated as security-sensitive."""
    return normalize_category(category) in SECURITY_CATEGORIES
